CREATE TABLE Universities(
  name VARCHAR(255),
  semester CHAR (3),
  location VARCHAR(255),
  time VARCHAR(255),
  capacity int
);

CREATE TABLE Universities(
  unitid INT,
  opeid INT,
  instnm VARCHAR(255),
  city VARCHAR(255),
);

UNITID	OPEID	INSTNM	CITY	STABBR	ZIP	ACCREDAGENCY	ACCREDCODE	INSTURL	NPCURL	NUMBRANCH	REGION	LOCALE	LATITUDE	LONGITUDE	MENONLY	WOMENONLY	AGE_ENTRY	AVGFACSAL	GRADS	FEMALE	MARRIED	UGDS_MEN	UGDS_WOMEN	SAT_AVG

CREATE TABLE Geography(

  city VARCHAR(255),

);

CREATE TABLE Locate(
  zip CHAR(5)
  city VARCHAR(255),


);
