CREATE TABLE College_info (
  UNITID INT,
  OPEID INT,
  INSTNM VARCHAR(255),
  CITY VARCHAR(50),
  STABBR CHAR(2),
  ZIP INT,
  ACCREDAGENCY VARCHAR(255),
  ACCREDCODE VARCHAR(10),
  INSTURL TEXT,
  NPCURL  TEXT,
  NUMBRANCH INT,
  REGION INT,
  LOCALE INT,
  LATITUDE DECIMAL(8,6),
  LONGITUDE	DECIMAL(8,6),
  MENONLY BOOLEAN,
  WOMENONLY BOOLEAN,
  AGE_ENTRY FLOAT,
  AVGFACSAL INT,
  GRADS INT,
  FEMALE DECIMAL(8,6),
  MARRIED DECIMAL(8,6),
  UGDS_MEN DECIMAL(8,6),
  UGDS_WOMEN DECIMAL(8,6),
  SAT_AVG INT,
  PRIMARY KEY (UNITID)
);

CREATE TABLE ACCREDAGENCY (
  NAME VARCHAR(255),
  STATUS VARCHAR(10),
  TYPE VARCHAR(100),
  PRIMARY KEY (NAME)
);
